<h1>Matrix Decomposition</h1>
# 0. Matrix


## 0.0 Left & Right Multiplication
Left multiplication a Matrix modifies the rows of the Matrix;

Right multiplication a Matrix modifies the columns of the Matrix;

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

print(B.dot(A))
print(A.dot(B))

[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


# 1. LU Matrix Decompostion
Decompostion a square matrix A to a <b>L</b>ower triangular matrix and an <b>U</b>pper triangular matrix.

> $A = U * V$

In [2]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P, L, U = lu(A)
print(P)
print(L)
print(U)

B = P.dot(L).dot(U)
print(B)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
[[ 1.          0.          0.        ]
 [ 0.14285714  1.          0.        ]
 [ 0.57142857  0.5         1.        ]]
[[  7.00000000e+00   8.00000000e+00   9.00000000e+00]
 [  0.00000000e+00   8.57142857e-01   1.71428571e+00]
 [  0.00000000e+00   0.00000000e+00  -1.58603289e-16]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
