<h1>Matrix Decomposition</h1>
# 0. Matrix


## 0.0 Left & Right Multiplication
Left multiplication a Matrix modifies the rows of the Matrix;

Right multiplication a Matrix modifies the columns of the Matrix.

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

print(B.dot(A))
print(A.dot(B))

[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


## 0.1 Matrix Derivative

Note: There are two different kind of ways to layout, numerator and denominator.

+ Numerator Layout

> The <b>row number</b> of result is the same with the column number of numerator, 

> and the column number of result is the same with the denominator.

+ Denominator Layout

> The <b>row number</b> of result is the same with the column number of denominator, 

> the column number of result is the same with the numerator.

I choose the <b>denominator</b> way, which expands the column of numerator in a row. 


### 0.1.0 Vector by scalar

> $\frac{\partial{\vec{x}}}{\partial{a}} 
= [\frac{\partial{x_1}}{\partial{a}}, 
\frac{\partial{x_2}}{\partial{a}},
...,
\frac{\partial{x_n}}{\partial{a}}]^T$

### 0.1.1 Scalar by vector

The column number of derivative result is 1, 

> $\frac{\partial{a}}{\partial{\vec{x}}}
= [\frac{\partial{a}}{\partial{x_1}}, 
\frac{\partial{a}}{\partial{x_2}},
...,
\frac{\partial{a}}{\partial{x_n}}]$

### 0.1.2 Vector by vector

The derivative result is the well-known Jacobbian Matrix.

> $\frac{\partial{\vec{y}}}{\partial{\vec{x}}} = [
\frac{\partial{y_1}}{\partial{\vec{x}}}, 
\frac{\partial{y_2}}{\partial{\vec{x}}}, 
...,
\frac{\partial{y_m}}{\partial{\vec{x}}}]^T$

> $ = [
[\frac{\partial{y_1}}{\partial{\vec{x_1}}}, 
\frac{\partial{y_1}}{\partial{\vec{x_2}}}, 
..., 
\frac{\partial{y_1}}{\partial{\vec{x_n}}}], 
[\frac{\partial{y_2}}{\partial{\vec{x_1}}}, 
\frac{\partial{y_2}}{\partial{\vec{x_2}}}, 
..., 
\frac{\partial{y_2}}{\partial{\vec{x_n}}}]
...
[\frac{\partial{y_m}}{\partial{\vec{x_1}}}, 
\frac{\partial{y_m}}{\partial{\vec{x_2}}}, 
..., 
\frac{\partial{y_m}}{\partial{\vec{x_n}}}]
]^T$


### 0.1.2 Vector multiplication by vector

### 0.1.2.0 $\vec{a}$ is not a function of $\vec{x}$

The result of $\vec{x}^T \vec{a}$ and $\vec{a}^T \vec{x}$ 
can be <b>assumed</b> to a scalar.

Hence, the derivative result is a column vector.

> $\frac{\partial{\vec{x}^T \vec{a}}}{\partial{\vec{x}}} =
\frac{\partial{\vec{a}^T \vec{x}}}{\partial{\vec{x}}} = \vec{a}$


> $\frac{\partial{\vec{b}^T A \vec{x}}}{\partial{\vec{x}}} = 
\frac{ \partial{ (A^T \vec{b})^T } \vec{x} } {\partial{x}} =
(A^T \vec{b})^T$

#### 0.1.2.1 $u$ and $v$ is function of $\vec{x}$

$u$ and $v$ is scalar and function of $\vec{x}$,
$u = u(\vec{x})$, $v = v(\vec{x})$, 

> $\frac{\partial{u + v}}{\partial{\vec{x}}}
= \frac{\partial{u}}{\partial{\vec{x}}}
+ \frac{\partial{v}}{\partial{\vec{x}}}$

> $\frac{\partial{u v}}{\partial{\vec{x}}} = 
u \frac{\partial{v}}{\partial{\vec{x}}} + 
v \frac{\partial{u}}{\partial{\vec{x}}}
$

<b>The Most Important Equation</b>

$\vec{u}$ and $\vec{v}$ is vector and function of $\vec{x}$,
$\vec{u} = \vec{u}(\vec{x})$, $\vec{v} = \vec{v}(\vec{x})$, 

> $\frac{\partial{(\vec{u} \bullet  \vec{v}})}{\partial{\vec{x}}} = 
\frac{\partial{\vec{u}^T \vec{v}}}{\partial{\vec{x}}} = 
\frac{\partial{\vec{u}}}{\partial{\vec{x}}} \vec{v} + 
\frac{\partial{\vec{v}}}{\partial{\vec{x}}} \vec{u}
$

Note: Think of the expanding way.

> $\frac{\partial{\vec{x}^T A \vec{x}}}{\partial{\vec{x}}} = 
\frac{\partial{(A^T\vec{x})^T \vec{x}}}{\partial{\vec{x}}}, 
(\vec{u} = A^T\vec{x}, \vec{v} = \vec{x})$

> $ = \frac{\partial{A^T\vec{x}}}{\partial{\vec{x}}} \vec{x} + 
\frac{\partial{\vec{x}}}{\partial{\vec{x}}} A^T\vec{x}$

> $ = A \vec{x} + A^T \vec{x}$

> $ = (A + A^T) \vec{x}$

# 1. LU Decomposition
Decomposite a square matrix A to a <b>L</b>ower triangular matrix and an <b>U</b>pper triangular matrix.

> $A = U * V$

If the first row of A is zero, then $a_{0,0} = u_{0, 0} * v_{0,0} = 0$, 

thus either $u_{0, 0}$ or $v_{0, 0}$ will be zero, which means that either $U$ or $V$ will be sigular.

Use a Permutation matrix $P$ to permutate $A$, then use the LU decomposition, 

> $P A = U * V$

> $A = P^{-1} * U * V = P * U * V, P^{-1} = P$

In [2]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P, L, U = lu(A)
print(P)
print(L)
print(U)

B = P.dot(L).dot(U)
print(B)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
[[ 1.          0.          0.        ]
 [ 0.14285714  1.          0.        ]
 [ 0.57142857  0.5         1.        ]]
[[  7.00000000e+00   8.00000000e+00   9.00000000e+00]
 [  0.00000000e+00   8.57142857e-01   1.71428571e+00]
 [  0.00000000e+00   0.00000000e+00  -1.58603289e-16]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


Use <b>Gaussian Elimination</b>.

# 2. QR Decomposition

Decomposite a non-square matrix $A$ to a Othogonal matrix $Q$ and an upper triangular matrix $R$. 

> $A = Q * R$

In [10]:
from scipy.linalg import qr

A = np.array([[1, 2], [3, 4], [5, 6]]) # (3, 2)
print(A)
print()

Q, R = qr(A)
print(Q)
print()
print(R)
print()

B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


Assume $\{a_1, a_2, ..., a_n\}$ are the columns of $A$, 

> $A = [a_1, a_2, ..., a_n]$

Project vector $u$ onto vector $v$, the projection is defined as, 

> $prod_v(u) = ||u|| \cos(u, b) b$

> $= ||u|| \frac{u^T b}{||u|| * ||b||} b$

> $= u^T b * b$

> $= u^T \frac{v}{||v||} * \frac{v}{||v||}$

> $= \frac{<u, v>}{<v, v>}v$

> $b = \frac{v}{||v||}, b^T b = b b^T = I, ||b|| = 1$

Compute $\{u_1, u_2, ..., u_n\}$ as follows,

> $u_1 = a_1, e_1 = \frac{u_1}{||u_1||}$

> $u_2 = a_2 - prod_{u_1}a_2, e_2 = \frac{u_2}{||u_2||}$

> $u_3 = a_3 - prod_{u_1}a_3 - prod_{u_2}a_3, e_3 = \frac{u_3}{||u_3||}$

> $...$

> $u_n = a_n - \sum_{j=1}^{n-1}prod_{u_j}a_n, e_n = \frac{u_n}{||u_n||}$

$\Longrightarrow$

> $a_1 = u_1 = prod_{e_1}u_1 = prod_{e_1}a_1 = \frac{<a_1, e_1>}{<e_1, e_1>}e_1 = e_1 <a_1, e_1>, <e_1, e_1> = 1$

> $a_2 = u_2 + prod_{u_1}a_2$

> $= prod_{e_2}u_2 + prod_{e_1}a_2$

> $= prod_{e_2}\{a_2 - prod_{u_1}a_2\} + prod_{e_1}a_2$

> $= prod_{e_2} a_2 + prod_{e_1} a_2$

> $= e_2<a_2, e_2> + e_1<a_2, e_1>$

> $...$

> $a_n = \sum_{j=1}^n e_j<a_n, e_j>$

Let $Q = [e_1, e_2, ..., e_n]$, $R = [r_1, r_2, ..., r_n]$, 

> $r_1 = [<a_1, e_1>, 0, ..., 0]$

> $r_2 = [<a_2, e_1>, <a_2, e_2>, 0, ..., 0]$

> $...$

> $r_n = [<a_n, e_1>, <a_n, e_2>, ..., <a_n, e_n>]$

Obtain the QR decomposition, 

> $A = Q * R$

# 3. Cholesky Decomposition

## 3.0 Cholesky Decomposition

Reference:

http://www.seas.ucla.edu/~vandenbe/133A/lectures/chol.pdf

Every positive definite matrix can be factored as, 

> $A = L L^T$

where $L$ is lower (or upper) triangular with positive diagonal components.

Using matrix blocks, 
> $A = [[A_{1,1}, A_{1, 2:n}]^T, [A_{2:n,1}, A_{2:n,2:n}]^T]$

> $=[[L_{1,1}, 0]^T, [L_{2:n, 1}, L_{2:n,2:n}]^T]$

> $[[L_{1,1}, L_{2:n, 1}^T]^T, [0, L_{2:n,2:n}^T]^T]$

> $= [[L_{1,1}^2, L_{1,1}L_{2:n, 1}^T]^T,
[L_{2:n, 1} L_{1,1},
L_{2:n, 1} L_{1,2}^T + L_{2:n,2:n}^T L_{2:n,2:n}]^T]$

$\Longrightarrow$

> $A_{1, 1} = L_{1, 1}^2$

> $A_{1, 2:n} = L_{1, 1}L_{2:n, 1}^T$

> $A_{2:n, 1} = L_{2:n, 1} L_{1,1}$

> $A_{2:n, 2:n} = L_{2:n, 1} L_{2:n, 1}^T
+ L_{2:n, 2:n} L_{2:n, 2:n}^T$

$\Longrightarrow$

> $L_{1, 1} = \sqrt{A_{1, 1}}$

> $L_{2:n, 1} = \frac{A_{2:n, 1}}{L_{1,1}}$

> $L_{2:n, 2:n} L_{2:n, 2:n}^T = A_{2:n, 2:n} - L_{2:n, 1} L_{2:n, 1}^T, (1)$

Equation (1) is another cholesky factorization of 
$A_{2:n, 2:n} - L_{2:n, 1} L_{2:n, 1}^T$ with order $n-1$.

Iterate to solve all of the orders of cholesky decomposition.

In order $k$, to compute the first column of current order,

which is the $j$-th ($k + j = n$) column of the original matrix $A$, 

In the current order, the current matrix becomes,

> $A_{i, i} = A_{i, i} - L_{i, :}L_{i, :}^T$

> $A_{j, i} = A_{j, i} - L_{i, :}L_{j, :}^T$

> $L_{i, i} = \sqrt { A_{i, i} }$

> $L_{i+1:n, i} = \frac{A_{i+1:n, i}}{L_{i, i}}$

In [31]:
import math

def my_cholesky(A):
    L = np.zeros(A.shape)
    
    n = A.shape[0]
    
    for i in range(n):
        L[i, i] = math.sqrt(A[i, i] - L[i, :].dot(L[i, :].T))
        
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - L[i, :].dot(L[j, :].T)) / L[i, i]
            
    return L
            
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
print()

L = my_cholesky(A)
print(L)
print()

print(L.dot(L.T))

[[2 1 1]
 [1 2 1]
 [1 1 2]]

[[ 1.41421356  0.          0.        ]
 [ 0.70710678  1.22474487  0.        ]
 [ 0.70710678  0.40824829  1.15470054]]

[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]


## 3.1 Application

If $A$ is real and positive definite, to solve, 

> $Ax = b$

Using Cholesky decomposition (lower triangular), 

> $A = LL^T$

Thus, the problem becomes, 

> $LL^Tx = b$

First, solve, 

> $Ly = b, L^Tx = y$

Finally, solve,

> $L^T x = y$

In [15]:
from scipy.linalg import cholesky

# A must be a positive-definite square matrix.
# A must be real positive symmetic.
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])

L = cholesky(A, lower=True)
print(L)
print()

B = L.dot(L.T)
print(B)

[[ 1.41421356  0.          0.        ]
 [ 0.70710678  1.22474487  0.        ]
 [ 0.70710678  0.40824829  1.15470054]]

[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]


# 4. Singular Value Decomposition

## 4.0 EigenValue & EigenVector

> $A x = \lambda x$, 

+ Equation for eigenvalue $\lambda$, 

> $det(A - \lambda I) = 0$, 

+ Equation for eigenvector $x$, 

> $(A - \lambda I) x = 0$

## 4.1 Diagonalizing Matrix

For eigen matrix $S$ made up of eigenvector 
> $S = [x_1, x_2, ..., x_n]$,

and a diagonal matrix $\Lambda$ made up of eigenvalue $\lambda_n$, 
$\Lambda_{i,i} = \lambda_{i}$, 

> $A S = A [x_1, x_2, ..., x_n]$

> $= [A x_1, A x_2, ..., A x_n]$

> $= [\lambda_1 x_1, \lambda_2 x_2, ..., \lambda_n x_n]$

> $= [x_1, x_2, ..., x_n] \Lambda$

> $= S \Lambda$

$\Longrightarrow$

> $\Lambda = S^{-1}AS$

Any matrix that has no repeated eigenvalues can be diagonalized.

## 4.2 Symmetric Matrix

If $A$ is a symmetric matrix, $A = A^T$, if $A$ is not singular, 

> $A = S \Lambda S^{-1}$

> $A^T = (S \Lambda S^{-1})^T = {S^{-1}}^T \Lambda S^T, \Lambda^T = \Lambda$

Because $A = A^T$, 

> $S \Lambda S^{-1} = (S^{-1})^T \Lambda S^T = (S^T)^{-1} \Lambda S^T$

<b>Possibly</b>, 

> $S^{-1} = S^T, \Longrightarrow S^T S = I$

> $S = (S^T)^{-1}, \Longrightarrow S S^T = I$

Thus, a symmetric matrix <b>can</b> be decomposited to orthogonal eigenvectors.

> $A = A^T$

> $A = Q \Lambda Q^T, Q^T = Q^{-1}$

## 4.3 Positive Definite Matrix

+ $A$ is <b>Positive Definite</b> if $x^T A x > 0$ for every nonzero $x$.




##  4.4 SVD

If a matrix $A$ is symmetric, it can be diagonalized by the eigenvectors.

> $A = S \Lambda S^{-1}$

But if $A$ is singular, it cannot be decomposited.

If $AA^T$ and $AA^T$ is nonsingular, 
let $U$ and $V$ be the eigenvectors of $AA^T$ and $A^TA$.

$(AA^T)^T = AA^T$, thus, $AA^T$ and $AA^T$ is symmetric matrix,
$U$ and $V$ can be chosen orthogonal,

> $AA^T = U \Lambda_1 U^{-1} = U \Lambda_1 U^T$

> $A^TA = V \Lambda_2 V^T$

+ SVD

For $A \in \mathbb{R}^{m \times n}$ and 
orthogonal matrix $U \in \mathbb{R}^{m \times m}$ and $V \in \mathbb{R}^{n \times n}$,

which is the eigenvectors of $AA^T \in \mathbb{R}^{m \times m}$ and $A^TA \in \mathbb{R}^{n \times n}$ respectively, 

$\Sigma \in \mathbb{R}^{m \times n}$ is a diagonal matrix, whose diagonal values are the eigenvalues of $M$ (often sorted descended),

> $A = U \Sigma V^T$

In [19]:
from scipy.linalg import svd

A = np.array([[1, 2, 3], [4, 5, 6]]) # (2 * 3)

U, Sigma, V = svd(A)
print(U)
print()

print(Sigma)
print()

print(V)
print()

# To save storage, diagonal matrix Sigma can be sorted in an array.
filled_Sigma = np.zeros(A.shape)

for i in range(Sigma.size):
    filled_Sigma[i][i] = Sigma[i]

B = U.dot(filled_Sigma).dot(V)
print(B)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

[ 9.508032    0.77286964]

[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
